services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - db_files:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

volumes:
  db_files:
    name: db_files
    driver: local
    driver_opts:
      device: /home/data/db_files
      o: bind
      type: none
  web:
    name: web
    driver: local
    driver_opts:
      device: /home/data/web
      o: bind
      type: none

networks:
  inception_net: