
version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
      # - /home/klamprak/data/web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - web:/var/www/html
      # - /home/klamprak/data/web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - db_files:/var/lib/mysql
      # - /home/klamprak/data/db_files:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception_net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s

# need to delete them on production with bind mounts
volumes:
  db_files:
  web:

networks:
  inception_net: