
version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

volumes:
  mariadb:

networks:
  inception_net: