
version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/osboxes/data/web:/var/www/html
      # - web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/osboxes/data/web:/var/www/html
      # - web:/var/www/html
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - /home/osboxes/data/db_files:/var/lib/mysql
      # - db_files:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception_net
    restart: always

# need to delete them on production with bind mounts
# volumes:
#   db_files:
#   web:

networks:
  inception_net: